syntax on
set tabstop=8
set cindent
set shiftwidth=8
filetype plugin indent on
set omnifunc=syntaxcomplete#Complete
set pastetoggle=<F10>
set showcmd
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
set modeline
set mouse=
set cursorline
set hls
set scrolloff=5
